### ISSUE TITLE
Create initial project structure

### ISSUE THREAD

**Issue by buzzfrog** [buzzfrog/SuperDuperImageFramework#1]
Create both source and test project.
Use this project structure:
<main>/src/SDImageFramework
<main>/test/SDImageFramework.Test

**Comment by CarlosSardo** [comment]
@buzzfrog I will pick this up.

**Comment by krist00fer** [comment]
@buzzfrog I'd love to work on this, can I? Please

**Comment by buzzfrog** [comment]
Sorry, I need to close this. Thanks for the help.
